name: Publish Docker image 

on:
  push:
    branches: ['main']

jobs:
  push_to_hub:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
      
      - name: Log in to Docker Hub
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PW }}
      
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
        with:
          images: roihan365/cerdashukumapi
      
      - name: Build and push Docker image
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

  deploy:
    runs-on: ubuntu-latest
    name: Continuous Deployment
    needs: [push_to_hub]
    steps:
      - name: Deploy using ssh
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.REMOTE_SERVER_ADDRESS }}
          username: ${{ secrets.REMOTE_SERVER_USERNAME }}
          password: ${{ secrets.REMOTE_SERVER_PASSWORD }}
          port: 22
          command_timeout: 200m
          script: |
            docker rm -f cerdashukumapi-container
            docker rmi roihan365/cerdashukumapi:main
            docker pull roihan365/cerdashukumapi:main
            docker run -d -p 8000:15400 --name cerdashukumapi-container roihan365/cerdashukumapi:main uvicorn app.main:app --host 0.0.0.0 --port 15400 --reload
